services:
  # ---------------------------
  # PostgreSQL
  # ---------------------------
  postgres:
    container_name: postgres-tdms
    image: 'postgres:16'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tdms_db
    volumes:
      - postgre_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - masterclass-tdms
  # ---------------------------
  # PGADMIN
  # ---------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-tdms
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_PREFIX: '/pgadmin'
    ports:
      - "15432:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - masterclass-tdms

  mail-dev:
    container_name: mail-dev-tdms
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - masterclass-tdms

networks:
  masterclass-tdms:
    driver: bridge

volumes:
  postgre_data:
    driver: local
  pgadmin_data: